language: csharp

rvm:
  - 2.0.0
  - jruby-head

env:
  global:
    - EnableNuGetPackageRestore=true

before_install:
  # https://github.com/travis-ci/travis-ci/issues/2839
  - export JAVA_HOME="$(/usr/libexec/java_home)"

script: "make"
